borrow code formatting utilities from the dealii project at 9.3.0-pre-3eef140804d4603fa5c204752b2c0f09b7d182ad
WIP: update indent scripts

diff --git a/utilities/indent b/utilities/indent
--- a/utilities/indent
+++ b/utilities/indent
@@ -1,7 +1,7 @@
 #!/bin/bash
 ## ---------------------------------------------------------------------
 ##
-## Copyright (C) 2012 - 2013, 2015 by the deal.II authors
+## Copyright (C) 2018 - 2020 by the deal.II authors
 ##
 ## This file is part of the deal.II library.
 ##
@@ -14,48 +14,78 @@
 ##
 ## ---------------------------------------------------------------------
 
-if test ! -d source ; then
-  echo "*** This script must be run from the top-level directory."
-  exit
+#
+# This script does the same thing as utilities/indent-all but only
+# reformats files which have changed (or have been added but neither
+# staged/committed) since the last merge commit to the master branch.
+#
+# The script needs to be executed as
+#   ./utilities/indent
+# from the top-level directory of the source tree, or via
+#   make indent
+# from a build directory.
+#
+# The script can be invoked with DEAL_II_CLANG_FORMAT to change
+# the default version of clang-format. For example:
+#   DEAL_II_CLANG_FORMAT=clang-format-6.0 ./utilities/indent
+# or,
+#   make DEAL_II_CLANG_FORMAT="clang-format-6.0" indent
+#
+# Note: If the script is invoked with REPORT_ONLY=true set,
+#   REPORT_ONLY=true ./utilities/indent
+# or,
+#   make REPORT_ONLY=true indent
+# then indentation errors will only be reported without any actual file
+# changes.
+#
+
+if [ ! -f utilities/indent_common.sh ]; then
+  echo "*** This script must be run from the top-level directory of deal.II."
+  exit 1
 fi
 
-if test ! -f utilities/astyle.rc ; then
-  echo "*** No style file utilities/astyle.rc found."
-  exit
+source utilities/indent_common.sh
+
+#
+# Run sanity checks:
+#
+
+checks
+
+if [ "x$1" == "xall" ]; then
+  EXECMD=process
+else
+  EXECMD=process_changed
 fi
 
-if test "`astyle --version 2>&1`" != "Artistic Style Version 2.04" ; then
-  echo "*** Found a version of astyle different than the required version 2.04."
-  exit
-fi
+#
+# process all source and header files:
+#
 
-# loop over all directories in which we may have source files;
-# collect a list of files and then spawn a parallel process to
-# indent all of them
-echo "--- Indenting all source files"
-for dir in source/* ; do
-  files=`find $dir | egrep '\.(cc|cpp|h)$'` ;
-  if test -n "$files" ; then
-    (astyle --options=utilities/astyle.rc $files ) &
-  fi
-done
+${EXECMD} "source header tests" ".*\.(cc|cpp|h|cu|cuh)" format_file
+${EXECMD} "source" ".*\.inst.in" format_inst
 
-echo "--- Indenting all header files"
-for dir in header/* ; do
-  files=`find $dir | egrep '\.(cc|cpp|h)$'` ;
-  if test -n "$files" ; then
-    (astyle --options=utilities/astyle.rc $files ) &
-  fi
-done
+#
+# Fix permissions and convert to unix line ending if necessary:
+#
 
-echo "--- Indenting all tests source and header files"
-for dir in tests/* ; do
-  files=`find $dir | egrep '\.(cc|cpp|h)$'` ;
-  if test -n "$files" ; then
-    (astyle --options=utilities/astyle.rc $files ) &
-  fi
-done
+${EXECMD} "source header tests ./CMakeLists.txt" \
+  ".*\.(cc|cpp|h|cu|cuh|inst.in|output.*|cmake|dox|txt)" fix_permissions
 
-# now wait for all of these processes to finish
-wait
+${EXECMD} "source header tests utilities ./CMakeLists.txt" \
+  ".*\.(cc|cpp|h|cu|cuh|inst.in|cmake|dox|txt|sh)" dos_to_unix
+
+#
+# Removing trailing whitespace
+#
+
+${EXECMD} "source header tests utilities ./CMakeLists.txt" \
+  ".*\.(cc|cpp|h|cu|cuh|cmake|dox|txt|sh)" remove_trailing_whitespace
+
+#
+# Ensure only a single newline at end of files
+#
+
+${EXECMD} "source header tests utilities ./CMakeLists.txt" \
+  ".*\.(cc|cpp|h|cu|cuh|html|dox|txt|sh)" ensure_single_trailing_newline
 
